language: php
jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: trusty
    - php: 7.0
      dist: trusty
    - php: 7.1
      dist: trusty
    - php: 7.2
      dist: trusty
    - php: 7.3
      dist: trusty
    - php: 7.4
      dist: trusty

sudo: required

before_script:
  - composer install
  - cd tests

script: ../vendor/bin/phpunit -v
